export const SCREEN_NAMES = Object.freeze({
  ADD_ADDRESS_SCREEN: "AddAddressScreen",
  ADDRESS_SCREEN: "AddressScreen",
  CART_SCREEN: "CartScreen",
  CART_STACK_NAV: "CartStack",
  CHECKOUT_SCREEN: "CheckoutScreen",
  HOME_SCREEN: "HomeScreen",
  HOME_STACK_NAV: "HomeStack",
  LOGIN_SCREEN: "LoginScreen",
  MAIN_TAB_NAV: "Main",
  PRODUCT_INFO_SCREEN: "ProductInfoScreen",
  PROFILE_SCREEN: "ProfileScreen",
  REGISTER_SCREEN: "RegisterScreen",
  SETTINGS_SCREEN: "SettingsScreen",
});
